# 连接mysql
spring:
  datasource.:
    url: jdbc:mysql://47.104.210.229:3307/studentmanager?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver#启用
  jpa:
    hibernate:
#      更新或者创建数据表结构
      ddl-auto: update
#    控制台显示SQL
    show-sql: true

server:
  port: 8080